name: Cypress Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cypress:
    runs-on: ubuntu-latest

    env:
      ENV: ${{ secrets.ENV }}
      USER_LOGIN: ${{ secrets.USER_LOGIN }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: |
          npx cypress run
